const actionType = Object.freeze({
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    CHANGE_LANGUAGE_APP: 'CHANGE_LANGUAGE',

    SITE_GET_LIST_ADDRESS_SUCCESS: 'SITE_GET_LIST_ADDRESS_SUCCESS',
    SITE_GET_LIST_ADDRESS_FAILED: 'SITE_GET_LIST_ADDRESS_FAILED',
});

export default actionType;
